all:
	# git add -A .
	# git commit -m "Phase 2:working on assignment 2" 
	# mkdir bin
	# cp assgn2_bplus_data.txt bin/assgn2_bplus_data.txt
	# cp a.txt bin/a.txt
	# cp bplustree.config bin/bplustree.config
	# cp sol.cpp bin/sol.cpp
	# cp querysample.txt bin/querysample.txt
	g++ sol.cpp -o sol
	./sol
clean:
	rm -rf bin/
	mkdir bin